apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
configMapGenerator:
- name: helloworld-demo
  files:
  - helloworld-demo.yaml
generatorOptions:
  disableNameSuffixHash: true